services:
  # gateway da aplicação
  kong:
    image: kong:latest
    env_file:
      - ./.env
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: ${KONG_ADMIN_HOST}:${KONG_ADMIN_PORT}
    volumes:
      - ./configurations/kong/kong.yml:/usr/local/kong/kong.yml
    ports:
      - "8000:8000"
      - "${KONG_ADMIN_PORT}:8001"
    expose:
      - "8000"
      - "${KONG_ADMIN_PORT}"
    depends_on:
      - user-microservice
    networks:
      - stock_microservice_network

  # microservices
  user-microservice:
    build: ./user-microservice
    env_file:
      - ./.env
    environment:
      DATABASE_URL: ${MONGO_URL}
    ports:
      - "${USER_APP_PORT}:8000"
    expose:
      - "${USER_APP_PORT}"
    networks:
      - stock_microservice_network

networks:
  stock_microservice_network:
    driver: bridge
